# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:

    white_october.tcpdf:
        class: WhiteOctober\TCPDFBundle\Controller\TCPDFController
        public: true
        arguments:
            $className: 'TCPDF'

    app.pdf.template.barcode:
        class: WhiteOctober\TCPDFBundle\Controller\BarcodeController
        public: true

    app.pdf.template.portrait:
        class: WhiteOctober\TCPDFBundle\Controller\PortraitController
        public: true

    app.pdf.template.hojaTrabajoNew:
        class: WhiteOctober\TCPDFBundle\Controller\hojaTrabajoNew
        public: true

    app.pdf.template.landscape:
        class: WhiteOctober\TCPDFBundle\Controller\LandscapeController
        public: true

    app.operations:
        class: App\Services\Operations
        arguments: ['@doctrine.orm.entity_manager']
        public: true

    app.mailer:
        class: App\Services\Mailer
        autowire: false
        arguments: ['@mailer', '@templating', '@session', '@doctrine.orm.entity_manager']
        public: true


    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    sensio_framework_extra.view.listener:
        alias: Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener

    App\Command\GetConsecutivoDiarioCommand:        
        tags: ['console.command']
    
    App\Command\GetConsecutivoMesCommand:
         tags: ['console.command']
    
    App\Command\GetConsecutivoSoloCommand:
         tags: ['console.command']