nelmio_cors:
  defaults:
    allow_credentials: true
    allow_origin: ["https://frontend-53doqfk88-clinilabs-projects.vercel.app"]
    allow_headers: ["Content-Type", "Authorization"]
    allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    expose_headers: []
    max_age: 3600
    hosts: []
    origin_regex: false
  paths:
    "^/":
      allow_origin: ["https://frontend-53doqfk88-clinilabs-projects.vercel.app"]
      allow_headers: ["Content-Type", "Authorization"]
      allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      max_age: 3600
